image: docker:stable

variables:
  REPOSITORY_URL: 779089996899.dkr.ecr.us-east-2.amazonaws.com/ncnt-sandbox

cache:
  paths:
  - node_modules/

services:
  - docker:dind

before_script:
  - docker info
  - apk add --no-cache curl jq python py-pip
  - pip install awscli
  
stages:
  - build

build:
  stage: build
  script:
    - $(aws ecr get-login --no-include-email --region us-east-1)
    - docker run --name ncent-postgres -e POSTGRES_PASSWORD=ncent -d postgres
    - docker build . -t ncent-sandbox
    - docker tag ncnt-sandbox:latest $REPOSITORY_URL:latest
    - docker push $REPOSITORY_URL
  only:
    - master
  tags:
    - docker
