image: docker:stable

variables:
  REPOSITORY_URL: 779089996899.dkr.ecr.us-east-2.amazonaws.com/ncnt-sandbox

cache:
  paths:
  - node_modules/

services:
  - docker:dind

before_script:
  - docker info
  - apk add --no-cache curl jq python py-pip
  - pip install awscli
  
stages:
  - build_production

build_production:
  stage: build_production
  script:
    - $(aws ecr get-login --no-include-email --region us-east-2)
    - docker build --build-arg DB_USERNAME=$PRODUCTION_DB_USERNAME --build-arg DB_PASSWORD=$PRODUCTION_DB_PASSWORD --build-arg DB_HOST=$PRODUCTION_DB_HOST --build-arg DB_PORT=$PRODUCTION_DB_PORT . -t ncent-sandbox
    - docker tag ncent-sandbox:latest $REPOSITORY_URL:latest
    - docker push $REPOSITORY_URL
  only:
    - master
  tags:
    - docker
